### PR TITLE
Added Firebase plugin

### PR DESCRIPTION
**Pull request by phretor**
* Added .gitignore
* Added Firebase plugin to check if an exposed Firebase configuration is found

### CODE REVIEW

**Comment by phretor** [comment]
BTW, for some reason, when using freshly-compiled plugins, this happens

```
$ ~/l9/l9explore$ l9explore service
l9explore: error: plugin.Open("/home/u/.l9/plugins/service/apachestatus_http"):
plugin was built with a different version of package internal/unsafeheader
```

I'm on go version go1.16.4 linux/amd64.

**Comment by gboddin** [comment]
Oh interesting !

Are you trying to use the binary version of l9explore ?

If that's the case that's the issue. The last stable version of l9explore was built using 1.16.3  ( https://github.com/LeakIX/l9explore/runs/2423829546?check_suite_focus=true#step:2:47 )

You either can rebuild l9explore for your go version ( ideal ) or downgrade your go version ( messy ).

**Comment by gboddin** [comment]
Hi !

Could you do a `git pull origin lib-firebase` to update your plugin to the final interface version ? :)

Thanks !

**Comment by gboddin** [comment]
Thanks again for the firebase plugin ! It's in master an should work as expected if it's fed the proper host-names ;)

**Comment by phretor** [comment]
😎

**Pull request merged**
